### ISSUE TITLE
IncomingMessageEvent just dies

### ISSUE THREAD

**Issue by Pocketpac** [WatchBeam/beam-client-java#14]
I'm having a weird issue and I I cant figure out what would be causing it. From time to time IncomingMessageEvent will stop producing messages, but the EVENT will continue to work sending 1 a second. I am confused by this because they both share the same thread, and if one locked up it should lock up the whole thread, causing my watcher thread to spot this and restart it. Is it possible it could be a weird issue in the beam-client-java?

**Comment by ttaylorr** [comment]
Hm, I was unable to produce this while testing.  One thing that sticks out to me though, your watcher thread.  This behavior of reconnecting on a disconnect is [built in](https://github.com/MCProHosting/beam-client-java/blob/master/src/main/java/pro/beam/api/resource/chat/BeamChatConnectable.java#L120-L128) to the client itself, and you shouldn't need to do that.  I would try the implementation on the client itself temporarily and see if the problem still persists.

**Comment by Pocketpac** [comment]
The thing is, I dont think it is "disconnecting" per say. Since you added the reconnect code it has drastically reduced the amount of times per day it reconnects. I have done tests forcing a thread to lock up in every which way I could think of, and it only ever effects that thread, the other channels remain uneffected, and the watcher thread does its thing and fixes the problem. But with this issue I continue to receive events but no longer receive messages. 

I have tested for stalled sql connection in the connection pool but neither the logs nor mysql ever show anything stalled or aborted, even after a massive reconnect. And I believe I states before it may not even be the api, I have a friend who built a bot using Node.JS and hosts several channels for TSSN and even he has the issue of random connection drops.

This particular issue thought I have only seen twice. Once was a few weeks ago and I just blamed it on the way I coded the bot, and went through and revamped it to be better, but this time, even with the bot not responding to a channel, the follower alert was still functioning and it was able to send the welcome message, so  I know the connection was still live.

**Comment by Pocketpac** [comment]
Update. I am making a chat client, and right now it just has a simple interface. I left it alone for awhile, and when I came back it had stopped responding to chat. All it does is take the message event and output it, slightly formatted, to a textfield, so I am certain now its not scottybot that causes the disconnects that dont cause your code to force a reconnect.

**Comment by Pocketpac** [comment]
Thought: When your code attempts to reconnect, does it re-auth as well? I cant find this code anywhere, but maybe it is there and I just am not noticing it.

**Comment by ttaylorr** [comment]
Oh, that might be the problem.

**Comment by Pocketpac** [comment]
I am playing with it some, and I am running into an issue, here is the code I'm playing with right now.        

    public void onClose(int i, String s, boolean b) {
                System.out.println("Closed, whoops");
        boolean Reconnecting = true;
        while (Reconnecting) {
            System.out.println("Beginning reconnect");
            this.uri = this.chat.selectEndpoint();
            System.out.println("Got uri");
            boolean connected = false;
            try {
                connected = this.connectBlocking();
                System.out.println("Connected");
            } catch (InterruptedException ex) {
                Logger.getLogger(BeamChatConnectable.class.getName()).log(Level.SEVERE, null, ex);
                
            }
            if (connected) {
            this.send(AuthInfo, null);
                Reconnecting = false;
            }

        }
    }

It makes it all the way to System.out.println("Got uri"); and then stalls.It never makes it to the Connected stage. I'm sure you will figure it out fast than I, but figured I would tinker with it until you pull some wizardry on it

**Comment by ttaylorr** [comment]
Hm, that would seem to indicate that the blocking connect operation is timing out.  How about we throw a time-limit on there and then try a different endpoint until it works?  Not too sure.

**Comment by Pocketpac** [comment]
how would one throw a time limit on something like that?

**Comment by Pocketpac** [comment]
After some experimenting i do not think catching and reconnect using the OnClose event will work. After a bunch of testing I determined the whole environment that is created dissapeares and the thread dies when the socket is closed. The only way I was able to get it to function was to import the whole project into scottybot instead of using it as a library and modify it to relaunch the thread when an OnClose event occurs. Might I recommend passing the OnClose to the client instead of keeping it internal to the api and just let the user of the api handle it?

**Comment by Pocketpac** [comment]
Under beamchatconnectable, I replace the onMessage method with this 
public void onMessage(String s) {

        ReplyPair replyPair = null;
        try {
            // Parse out the generic JsonObject so we can pull out the ID element from it,
            //  since we cannot yet parse as a generic class.
            JsonObject e = this.beam.gson.fromJson(s, JsonObject.class);
            if (e.has("id")) {
                int id = e.get("id").getAsInt();

                // Try and remove a reply-pair, execute the #onSuccess method if we find
                // a matching reply-pair.
                if ((replyPair = this.replyHandlers.remove(id)) != null) {
                    Class<? extends AbstractChatDatagram> type = replyPair.type;

                    // Now that we have the type, we can appropriately parse out the value
                    // And call the #onSuccess method with the value.
                    AbstractChatDatagram datagram = this.beam.gson.fromJson(s, type);
                    replyPair.handler.onSuccess(type.cast(datagram));
                }
            } else if (e.has("event")) {
                String eventName = e.get("event").getAsString();
                Class<? extends AbstractChatEvent> type = AbstractChatEvent.EventType.fromSerializedName(eventName).getCorrespondingClass();

                this.dispatchEvent(this.beam.gson.fromJson(e, type));
            }
        } catch (Exception e) {
            System.err.println(e.getCause() + " |||| " + e.getMessage());
            // call the #onFailure method with the throwable.
//            if (replyPair != null) {
//                replyPair.handler.onFailure(e);
//            } else {
//                throw e;
//            }
        }

I commended out everything in the catch and just had it dump an error, and the issue seems to have gone away. What does this do and why is it needed?

**Comment by ttaylorr** [comment]
The reason the issue went away is that the commented-out part is responsible for propagating the issue down to the handler.

**Comment by Pocketpac** [comment]
I figured that, but why? Does it serve some purpose and I need it for some reason?

**Comment by ttaylorr** [comment]
Sadly can't reproduce this locally, however if the issue appears again, I'll reopen the issue and do my best to fix it :smile:
