### ISSUE TITLE
Make BeamChannel implement Serializable

### ISSUE THREAD

**Issue by optisamit** [WatchBeam/beam-client-java#16]
It is needed, for example, in Android client, to persist list of channels during an Activity re-creation.
Maybe other classes should have this interface, too.

**Comment by optisamit** [comment]
@ttaylorr Please mark as serializable all the types that are referenced by the class' fields. Otherwise serialization mechanism will not work

**Comment by ttaylorr** [comment]
Will do shortly, or you can take over in the meantime if you'd like. Busy with the deploy today :/

**Comment by optisamit** [comment]
@ttaylorr I'm sorry, I have some troubles with my IDE. Please be sure to update all referenced types to the deepmost level. This includes changing some interfaces to Serializable classes (e.g. List -> ArrayList). Thanks

**Comment by ttaylorr** [comment]
[All done](https://github.com/WatchBeam/beam-client-java/commit/8cb14fbb197b361a45b2bc7e9ec084dec63daefb)!
