### ISSUE TITLE
Gson Date Format Error

### ISSUE THREAD

**Issue by Thelonedevil** [WatchBeam/beam-client-java#31]
With the recent API changes we at Otbproject have encountered this: https://gist.github.com/NthPortal/c679151c8234bef666b9

A fix for this is to replace, in the Beam API constructor:
this.gson = new GsonBuilder().create();

With this:
this.gson = new GsonBuilder().setDateFormat("yyyy-MM-dd HH:mm:ss").create());

**Comment by ttaylorr** [comment]
This makes sense.  There are a few parts of the client that are broken with the newest release, and I'll make a new release of the client shortly to match with the changes.

**Comment by ttaylorr** [comment]
Okay, this issue will get closed with #32.
