### ISSUE TITLE
Joiner for IncomingMessageData

### ISSUE THREAD

**Issue by NthPortal** [WatchBeam/beam-client-java#37]
I'm curious to know why you join on a space character [here](https://github.com/WatchBeam/beam-client-java/blob/ad5c0eede5e4865c5ce9467d045aaadf0d68598d/src/main/java/pro/beam/api/resource/chat/events/data/IncomingMessageData.java#L27), rather than joining on an empty string. Joining on a space character creates extra empty spaces before and after links, emoticons, etc., so that you end up with double spaces (or unexpected single spaces in the middle of a link if the link isn't parsed correctly).

**Comment by ttaylorr** [comment]
Ah, sorry!  That's my bad -- that commit should fix it :smile:
